In [1]:
import duckdb
import pandas as pd
from pathlib import Path
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller
from pmdarima import auto_arima

In [2]:
db_path = Path(f'{Path.cwd()}/sm_db.duckdb')
print(f"cwd: {Path.cwd()} \n filepaht: {db_path}")
db_path.exists()
conn = duckdb.connect(db_path, read_only=True)
stroke_mortality_clean = conn.sql("SELECT  * FROM stroke_mortality;").df()

cwd: c:\Data_Analysis_Projects\HHS_data_analysis\analysis\stroke_mortality_analysis
 filepaht: c:\Data_Analysis_Projects\HHS_data_analysis\analysis\stroke_mortality_analysis\sm_db.duckdb

In [3]:
stroke_mortality_clean.head()

,id,api_id,year,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
0,1490899,row-9mxu_6uqv-j4kv,2004,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,41.0,Coronary heart disease (CHD)
1,1490900,row-rgch~giks_tdv8,2017,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,39.4,Coronary heart disease (CHD)
2,1490901,row-asyv_kbrc-barf,1999,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,52.6,Coronary heart disease (CHD)
3,1490902,row-6scm_2i8j.jaqv,2019,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,38.0,Coronary heart disease (CHD)
4,1490903,row-dx4n~f74v_k85s,2018,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,40.7,Coronary heart disease (CHD)

In [4]:
stroke_mortality_clean['sex'] = stroke_mortality_clean['sex'].replace('Men', 'Male')
stroke_mortality_clean['sex'] = stroke_mortality_clean['sex'].replace('Women', 'Female')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('American Indian or Alaska Native', 'American Indian/Alaska Native')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Black', 'Black (Non-Hispanic)')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Asian', 'Asian/Pacific Islander')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Native Hawaiian or Other Pacific Islander', 'Asian/Pacific Islander')

In [5]:
stroke_mortality_clean['race'].unique()

<StringArray>
[                      'Overall',                         'White',
          'Black (Non-Hispanic)',                      'Hispanic',
        'Asian/Pacific Islander', 'American Indian/Alaska Native',
            'More than one race']
Length: 7, dtype: str

In [6]:
stroke_mortality_clean['sex'].unique()

<StringArray>
['Female', 'Overall', 'Male']
Length: 3, dtype: str

In [7]:
stroke_mortality_clean['location'] = stroke_mortality_clean['location'].str.replace('County', '' ,regex=False).str.strip()

In [8]:
stroke_mortality_clean['location'].unique()

<StringArray>
[     'Schuyler',        'Shelby',         'Piatt',     'Vermilion',
     'Anchorage',         'White',          'Pike',      'Randolph',
        'Wabash',         'Iosco',
 ...
 'West Virginia',    'Sweetwater',         'Uinta',      'Washakie',
        'Weston',   'Puerto Rico',       'Newport',    'Providence',
  'Rhode Island',  'South Dakota']
Length: 2061, dtype: str

In [9]:
stroke_mortality_clean.count()

id           5417584
api_id       5417584
year         5417584
state        5417584
location     5417584
geo_level    5417584
rate         5417584
sex          5417584
race         5417584
fips         5417584
icd_class    5417584
value        3162919
topic        5407824
dtype: int64

In [10]:
stroke_mortality_clean = stroke_mortality_clean.dropna()

In [11]:
stroke_mortality_clean.count()

id           3157962
api_id       3157962
year         3157962
state        3157962
location     3157962
geo_level    3157962
rate         3157962
sex          3157962
race         3157962
fips         3157962
icd_class    3157962
value        3157962
topic        3157962
dtype: int64

In [12]:
stroke_mortality_clean.head()

,id,api_id,year,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
0,1490899,row-9mxu_6uqv-j4kv,2004,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,41.0,Coronary heart disease (CHD)
1,1490900,row-rgch~giks_tdv8,2017,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,39.4,Coronary heart disease (CHD)
2,1490901,row-asyv_kbrc-barf,1999,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,52.6,Coronary heart disease (CHD)
3,1490902,row-6scm_2i8j.jaqv,2019,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,38.0,Coronary heart disease (CHD)
4,1490903,row-dx4n~f74v_k85s,2018,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,40.7,Coronary heart disease (CHD)

In [13]:
stroke_mortality_clean.count()

id           3157962
api_id       3157962
year         3157962
state        3157962
location     3157962
geo_level    3157962
rate         3157962
sex          3157962
race         3157962
fips         3157962
icd_class    3157962
value        3157962
topic        3157962
dtype: int64

In [ ]:
Nj_Stroke_Mortality_Overall = stroke_mortality_clean[
    (stroke_mortality_clean['sex'] == 'Overall') &
    (stroke_mortality_clean['race'] == 'Overall') &
    (stroke_mortality_clean['state'] == 'NJ') &
    (stroke_mortality_clean['topic'].isin(['All stroke', 'Stroke Mortality']))
].copy()

In [ ]:
Nj_Stroke_Mortality_Overall = Nj_Stroke_Mortality_Overall.sort_values('year')
Nj_Stroke_Mortality_Overall['year'] = pd.to_datetime(Nj_Stroke_Mortality_Overall['year'],format='%Y')
NNj_Stroke_Mortality_Overall = Nj_Stroke_Mortality_Overall[(Nj_Stroke_Mortality_Overall['geo_level'] == 'County')]

In [ ]:
Nj_Stroke_Mortality_Overall

,id,api_id,year,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
1606551,3347094,row-a7td_b8gk.fv3g,1999-01-01,NJ,Cape May,County,"per 100,000",Overall,Overall,34009,Cardiovascular Diseases,14.8,All stroke
1612290,3366356,row-3jeb_5bui-45ay,1999-01-01,NJ,Mercer,County,"per 100,000",Overall,Overall,34021,Cardiovascular Diseases,16.4,All stroke
1598487,3338689,row-z4ss~pzhz.ts5z,1999-01-01,NJ,Bergen,County,"per 100,000",Overall,Overall,34003,Cardiovascular Diseases,337.1,All stroke
1596803,3335321,row-yk4c_q8ww-xpga,1999-01-01,NJ,Atlantic,County,"per 100,000",Overall,Overall,34001,Cardiovascular Diseases,366.6,All stroke
1636787,3362754,row-ex9x.5i8e_k2ym,1999-01-01,NJ,Warren,County,"per 100,000",Overall,Overall,34041,Cardiovascular Diseases,11.0,All stroke
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3075404,333107,row-vcfa~n62d~wbem,2023-01-01,NJ,Burlington,County,"per 100,000 population",Overall,Overall,34005,Cardiovascular Diseases,68.7,Stroke Mortality
3075403,333106,row-qxba.z3gs_usk4,2023-01-01,NJ,Bergen,County,"per 100,000 population",Overall,Overall,34003,Cardiovascular Diseases,45.1,Stroke Mortality
3075402,333105,row-67fa_65wd-d8ns,2023-01-01,NJ,Atlantic,County,"per 100,000 population",Overall,Overall,34001,Cardiovascular Diseases,55.5,Stroke Mortality
3075422,333125,row-xvtq~a4ad~gu4m,2023-01-01,NJ,Warren,County,"per 100,000 population",Overall,Overall,34041,Cardiovascular Diseases,54.5,Stroke Mortality
3075411,333114,row-t9vi.z7bi_2fpb,2023-01-01,NJ,Hunterdon,County,"per 100,000 population",Overall,Overall,34019,Cardiovascular Diseases,46.7,Stroke Mortality

In [ ]:
Nj_Stroke_Mortality_Overall.count()

id           924
api_id       924
year         924
state        924
location     924
geo_level    924
rate         924
sex          924
race         924
fips         924
icd_class    924
value        924
topic        924
dtype: int64

In [ ]:
county_year = (Nj_Stroke_Mortality_Overall.groupby(['year', 'location'])['value'].mean().rename('county_rate'))
nj_state = (county_year.groupby('year').mean().rename('stroke_rate'))
nj_state.index = pd.to_datetime(nj_state.index, format='%Y')
nj_state

year
1999-01-01    181.857143
2000-01-01    187.959524
2001-01-01    176.040476
2002-01-01    173.078571
2003-01-01    167.678571
2004-01-01    157.459524
2005-01-01    149.823810
2006-01-01    140.135714
2007-01-01    137.721429
2008-01-01    127.442857
2009-01-01    125.790476
2010-01-01    125.023810
2011-01-01    127.145238
2012-01-01    124.435714
2013-01-01    122.650000
2014-01-01    120.550000
2015-01-01    120.850000
2016-01-01    118.904762
2017-01-01    117.809524
2018-01-01    115.733333
2019-01-01    115.097619
2020-01-01     63.580952
2023-01-01     57.876190
Name: stroke_rate, dtype: float64

In [19]:
# nj_state.count()

In [20]:
county_year.count()

np.int64(483)

In [21]:
county_year

year        location
1999-01-01  Atlantic      193.30
            Bergen        174.20
            Burlington    192.50
            Camden        188.50
            Cape May      172.55
                           ...
2023-01-01  Salem          73.90
            Somerset       55.20
            Sussex         50.10
            Union          62.80
            Warren         54.50
Name: county_rate, Length: 483, dtype: float64